scorecard:
  # Setting a global scorecard option
  bundle: deploy/olm-catalog/health-service-operator
  plugins:
    - basic:
        namespace: "health-service-operator"
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml"
        csv-path: "deploy/olm-catalog/health-service-operator/3.5.0/health-service-operator.v3.5.0.clusterserviceversion.yaml"
