###############################################################################
# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2019, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: system-healthcheck-service-config
data:
  cpnames.yaml: |
    cpnames:
    - fullname: IBM Cloud Platform Common Services
      shortname: cs
    - fullname: IBM Cloud Pak for Multicloud Management
      shortname: cp4mcm
    - fullname: IBM Cloud Pak for Integration
      shortname: cp4i
    - fullname: IBM Cloud Pak for Data
      shortname: cp4d
    - fullname: IBM Cloud Pak for Automation
      shortname: cp4a
    - fullname: IBM Cloud Pak for Applications
      shortname: cp4app
    - fullname: undefined
      shortname: undefined