apiVersion: operator.ibm.com/v1alpha1
kind: HealthService
metadata:
  name: system-healthcheck-service
spec:
  memcached:
    name: icp-memcached
    image:
      repository: quay.io/opencloudio/icp-memcached
      tag: 3.5.0
    replicaCount: 1
    serviceAccountName: ibm-healthcheck-operator-cluster
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    command:
    - memcached
    - -m 64
    - -o
    - modern
    - -v
  healthService:
    name: system-healthcheck-service
    configmapName: system-healthcheck-service-config
    image:
      repository: quay.io/opencloudio/system-healthcheck-service
      tag: 3.5.0
    replicaCount: 1
    serviceAccountName: ibm-healthcheck-operator-cluster
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    hostNetwork: false
    #cloudpakNameSetting: Labels/Annotations:name
    #serviceNameSetting: Labels/Annotations:name
    #dependsSetting: Labels/Annotations:name
