apiVersion: operator.ibm.com/v1alpha1
kind: MustGatherConfig
metadata:
  name: default
spec:
  gatherConfig: |-
    modules="overview,system,failure,ocp,cloudpak"
    namespaces="common-service,ibm-common-services"
    labels=""

---
apiVersion: operator.ibm.com/v1alpha1
kind: MustGatherConfig
metadata:
  name: common-service
spec:
  gatherConfig: |-
    modules="overview,failure,cloudpak"
    namespaces="common-service,ibm-common-services"
    labels=""