apiVersion: operator.ibm.com/v1alpha1
kind: HealthService
metadata:
  name: system-healthcheck-service
  labels:
    app.kubernetes.io/instance: system-healthcheck-service
    app.kubernetes.io/managed-by: ibm-healthcheck-operator
    app.kubernetes.io/name: ibm-healthcheck-operator
spec:
  memcached:
    name: icp-memcached
    image:
      name: icp-memcached
      repository: quay.io/opencloudio
      tag: 3.5.0
    replicaCount: 1
    serviceAccountName: ibm-healthcheck-operator-cluster
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    command:
    - memcached
    - -m 64
    - -o
    - modern
    - -v
  healthService:
    name: system-healthcheck-service
    configmapName: system-healthcheck-service-config
    image:
      name: system-healthcheck-service
      repository: quay.io/opencloudio
      tag: 3.5.0
    replicaCount: 1
    serviceAccountName: ibm-healthcheck-operator-cluster
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    hostNetwork: false
    #cloudpakNameSetting: Labels/Annotations:name
    serviceNameSetting: Annotations:productName
    #dependsSetting: Labels/Annotations:name
