apiVersion: operator.ibm.com/v1alpha1
kind: MustGatherJob
metadata:
  name: example-mustgatherjob
spec:
  serviceAccountName: ibm-mustgather-admin
  mustgatherConfigName: common-service
#  image:
#    repository: quay.io/haoqing/must-gather
#    tag: latest
